In [1]:
#Project 2 Lede Program
#Marcela Vilar Mota Santos

In [113]:
import requests
import pandas as pd
from dotenv import load_dotenv
import os
from opensky_api import OpenSkyApi, TokenManager
import geocoder
from datetime import datetime, timezone
import json

## getting the data from the world cup matches and basic info about the world cup

In [3]:
url = "https://www.zoho.com/toolkit/fifa-world-cup-2026.html?zredirect=f&zsrc=langdropdown&lb=pt-br&lb=pt-br"

In [4]:
table = pd.read_html(url)

In [119]:
stadiums = table[0]
stadiums.head(3)

,Host Country,City,Venue,Net Capacity
0,United States,New York/New Jersey,New York New Jersey Stadium,78576
1,United States,Kansas City,Kansas City Stadium,67513
2,United States,San Francisco Bay Area,San Francisco Bay Area Stadium,69391

In [122]:
stadiums.shape

(16, 4)

In [120]:
stadiums.sort_values(by="Net Capacity", ascending=False)
#New York New Jersey Stadium biggest stadium

,Host Country,City,Venue,Net Capacity
0,United States,New York/New Jersey,New York New Jersey Stadium,78576
13,Mexico,Mexico City,Mexico City Stadium,72766
6,United States,Dallas,Dallas Stadium,70122
7,United States,Los Angeles,Los Angeles Stadium,69650
2,United States,San Francisco Bay Area,San Francisco Bay Area Stadium,69391
5,United States,Houston,Houston Stadium,68311
1,United States,Kansas City,Kansas City Stadium,67513
3,United States,Atlanta,Atlanta Stadium,67382
8,United States,Philadelphia,Philadelphia Stadium,65827
10,United States,Seattle,Seattle Stadium,65123
4,United States,Miami,Miami Stadium,64091
9,United States,Boston,Boston Stadium,63815
14,Mexico,Monterrey,Monterrey Stadium,50113
11,Canada,Vancouver,BC Place Vancouver,48821
15,Mexico,Guadalajara,Guadalajara Stadium,44330
12,Canada,Toronto,Toronto Stadium,44315

In [6]:
prize = table[4]
prize.head(3)

       Final Position Prize Money (per Team)
0  Champions (Winner)            $50 million
1           Runner-up            $33 million
2         Third place            $29 million

In [7]:
groups = table[5]
groups.head(3)

     Group                              Participating Nations
0  Group A         Mexico, South Africa, South Korea, Czechia
1  Group B  Canada, Bosnia and Herzegovina, Switzerland, Q...
2  Group C                   Brazil, Morocco, Scotland, Haiti

In [8]:
matches = table[6][1:]
matches.head(3)

,Match,Date,Day,Group Stage,Team 1,vs,Team 2,Venue,City,Region
1,1,Jun 11,Thu,A,Mexico,vs,South Africa,Mexico City Stadium,Mexico City,Central
2,2,Jun 11,Thu,A,South Korea,vs,Czech Republic,Estadio Guadalajara,Guadalajara,Central
3,3,Jun 12,Fri,B,Canada,vs,Bosnia and Herzegovina,Toronto Stadium,Toronto,Eastern

In [121]:
matches.tail(5)

,Match,Date,Team 1,Team 2,Venue,City,phase
106,102,2026-07-15,Winner Match 99,Winner Match 100,Atlanta Stadium,Atlanta,Semifinals
107,"THIRD-PLACE MATCH (July 18, 2026)",NaT,"THIRD-PLACE MATCH (July 18, 2026)","THIRD-PLACE MATCH (July 18, 2026)","THIRD-PLACE MATCH (July 18, 2026)","THIRD-PLACE MATCH (July 18, 2026)",None
108,103,2026-07-18,Loser Match 101,Loser Match 102,Miami Stadium,Miami,Third Place
109,"FINAL (July 19, 2026)",NaT,"FINAL (July 19, 2026)","FINAL (July 19, 2026)","FINAL (July 19, 2026)","FINAL (July 19, 2026)",None
110,104,2026-07-19,Winner Match 101,Winner Match 102,New York New Jersey Stadium,New York/NJ,Final

In [9]:
#droping columns
matches = matches.drop(columns =['Day','Group Stage', 'vs', "Region"])

In [10]:
matches.head(3)

,Match,Date,Team 1,Team 2,Venue,City
1,1,Jun 11,Mexico,South Africa,Mexico City Stadium,Mexico City
2,2,Jun 11,South Korea,Czech Republic,Estadio Guadalajara,Guadalajara
3,3,Jun 12,Canada,Bosnia and Herzegovina,Toronto Stadium,Toronto

In [11]:
len(matches)

110

In [12]:
#finding irregular columns
matches["Match"][109]

'FINAL (July 19, 2026)'

In [13]:
matches["Match"][107]

'THIRD-PLACE MATCH (July 18, 2026)'

In [14]:
matches["Match"][104]

'SEMI-FINALS (July 14 – July 15, 2026)'

In [15]:
matches["Match"][99]

'QUARTER-FINALS (July 9 – July 11, 2026)'

In [16]:
matches["Match"][90]

'ROUND OF 16 (July 4 – July 7, 2026)'

In [17]:
matches["Match"][73]

'ROUND OF 32 (June 28 – July 3, 2026)'

In [18]:
#converting to datetime format
#adding the year and converting to datetime
matches["Date"] = pd.to_datetime(matches["Date"], format="%b %d", errors="coerce")

#formating as MM-DD-YYYY
matches["Date"] = matches["Date"].dt.strftime("%m-%d-2026")

In [19]:
matches.head(3)

,Match,Date,Team 1,Team 2,Venue,City
1,1,06-11-2026,Mexico,South Africa,Mexico City Stadium,Mexico City
2,2,06-11-2026,South Korea,Czech Republic,Estadio Guadalajara,Guadalajara
3,3,06-12-2026,Canada,Bosnia and Herzegovina,Toronto Stadium,Toronto

## separating by phase 
##### project due date is july 12, so i can only analyse until the end of the round of 16 (july 7) and maybe quarter finals (july 11)

In [20]:
#creating a new empty column
matches["phase"] = None

In [21]:
matches.head(3)

,Match,Date,Team 1,Team 2,Venue,City,phase
1,1,06-11-2026,Mexico,South Africa,Mexico City Stadium,Mexico City,None
2,2,06-11-2026,South Korea,Czech Republic,Estadio Guadalajara,Guadalajara,None
3,3,06-12-2026,Canada,Bosnia and Herzegovina,Toronto Stadium,Toronto,None

In [22]:
matches["Date"].dtype

In [23]:
#transforming to datetime element so the for loop works
matches["Date"] = pd.to_datetime(matches['Date'])

In [24]:
matches["Date"].dtype

dtype('<M8[us]')

In [25]:
#filling the new column
for index, row in matches.iterrows(): 
    if pd.Timestamp("2026-06-11") <= row["Date"] <= pd.Timestamp("2026-06-27"):
       matches.at[index, "phase"] = "Group Stage"
    elif pd.Timestamp("2026-06-28") <= row["Date"] <= pd.Timestamp("2026-07-03"):
       matches.at[index, "phase"] = "Round of 32"
    elif pd.Timestamp("2026-07-04") <= row["Date"] <= pd.Timestamp("2026-07-07"):
       matches.at[index, "phase"] = "Round of 16"
    elif pd.Timestamp("2026-07-09") <= row["Date"] <= pd.Timestamp("2026-07-11"):
       matches.at[index, "phase"] = "Quarterfinals"
    elif pd.Timestamp("2026-07-14") <= row["Date"] <= pd.Timestamp("2026-07-15"):
       matches.at[index, "phase"] = "Semifinals"
    elif pd.Timestamp("2026-07-18") == row["Date"]:
       matches.at[index, "phase"] = "Third Place"
    elif pd.Timestamp("2026-07-19") == row["Date"]:
       matches.at[index, "phase"] = "Final"

In [26]:
matches["phase"].unique()

array(['Group Stage', None, 'Round of 32', 'Round of 16', 'Quarterfinals',
       'Semifinals', 'Third Place', 'Final'], dtype=object)

In [27]:
matches[matches["phase"].isna()]

,Match,Date,Team 1,Team 2,Venue,City,phase
73,"ROUND OF 32 (June 28 – July 3, 2026)",NaT,"ROUND OF 32 (June 28 – July 3, 2026)","ROUND OF 32 (June 28 – July 3, 2026)","ROUND OF 32 (June 28 – July 3, 2026)","ROUND OF 32 (June 28 – July 3, 2026)",None
90,"ROUND OF 16 (July 4 – July 7, 2026)",NaT,"ROUND OF 16 (July 4 – July 7, 2026)","ROUND OF 16 (July 4 – July 7, 2026)","ROUND OF 16 (July 4 – July 7, 2026)","ROUND OF 16 (July 4 – July 7, 2026)",None
99,"QUARTER-FINALS (July 9 – July 11, 2026)",NaT,"QUARTER-FINALS (July 9 – July 11, 2026)","QUARTER-FINALS (July 9 – July 11, 2026)","QUARTER-FINALS (July 9 – July 11, 2026)","QUARTER-FINALS (July 9 – July 11, 2026)",None
104,"SEMI-FINALS (July 14 – July 15, 2026)",NaT,"SEMI-FINALS (July 14 – July 15, 2026)","SEMI-FINALS (July 14 – July 15, 2026)","SEMI-FINALS (July 14 – July 15, 2026)","SEMI-FINALS (July 14 – July 15, 2026)",None
107,"THIRD-PLACE MATCH (July 18, 2026)",NaT,"THIRD-PLACE MATCH (July 18, 2026)","THIRD-PLACE MATCH (July 18, 2026)","THIRD-PLACE MATCH (July 18, 2026)","THIRD-PLACE MATCH (July 18, 2026)",None
109,"FINAL (July 19, 2026)",NaT,"FINAL (July 19, 2026)","FINAL (July 19, 2026)","FINAL (July 19, 2026)","FINAL (July 19, 2026)",None

In [28]:
matches["phase"].value_counts() #checking if it worked

phase
Group Stage      72
Round of 32      16
Round of 16       8
Quarterfinals     4
Semifinals        2
Third Place       1
Final             1
Name: count, dtype: int64

In [29]:
matches.to_csv("matches.csv", index=False)

## hiding my geocoder API key

In [30]:
#hiding my api key
# create a file called `.env` (# it's a hidden file)
# you also will want to create a file called .gitignore (it is also hidden)
# and put this in it (without the #)
# .env 
# that's to tell Git not to put your .env file (with your API key) onto Github

In [31]:
load_dotenv()

True

In [32]:
ls

 O volume na unidade C ‚ OS
 O N£mero de S‚rie do Volume ‚ 44F5-4363

 Pasta de C:\Users\samue\OneDrive\Desktop\Lede\Projects\world cup

07/09/2026  07:41 AM    <DIR>          .
07/06/2026  02:54 PM    <DIR>          ..
07/08/2026  06:58 PM               116 .env
07/05/2026  11:58 PM             4,706 .gitignore
07/08/2026  05:00 PM    <DIR>          .ipynb_checkpoints
07/05/2026  11:49 PM                60 api key geocoder.txt
07/08/2026  07:27 PM                83 credentials.json
07/08/2026  03:59 PM             7,611 df_geo.csv
07/03/2026  05:04 PM             4,727 extract_worldcup.py
07/03/2026  03:59 PM            44,443 fifa-world-cup-2026.ics
07/08/2026  05:00 PM             3,127 first_matches.csv
07/09/2026  07:41 AM             9,399 matches.csv
07/03/2026  06:23 PM               137 mentorship july 3.txt
07/05/2026  11:53 PM                60 untitled.txt
07/09/2026  07:41 AM           542,214 worldcup.ipynb
07/03/2026  05:09 PM            28,228 worldcup_PDF.ipynb
07/08/2026  11:30 AM            29,414 worldcup_test.ipynb
07/03/2026  04:06 PM         5,250,535 worldcupcalendar.pdf
              15 arquivo(s)      5,924,860 bytes
               3 pasta(s)   53,825,269,760 bytes dispon¡veis

In [33]:
api_key_geocoder = os.environ["api_key_geocoder"]

In [34]:
api_key_geocoder[:9]+"..."

'AIzaSyDI7...'

In [35]:
#making a new df with only the venue and city, because it may be easier for the geocoder to read 
df_geo = matches[['Venue', 'City']]
df_geo.head(3)

                 Venue         City
1  Mexico City Stadium  Mexico City
2  Estadio Guadalajara  Guadalajara
3      Toronto Stadium      Toronto

In [36]:
#getting the country so geocoder would work
stadiums.head(3)

,Host Country,Host City,Official FIFA Stadium Designation,Net Capacity
0,United States,New York/New Jersey,New York New Jersey Stadium,78576
1,United States,Kansas City,Kansas City Stadium,67513
2,United States,San Francisco Bay Area,San Francisco Bay Area Stadium,69391

In [37]:
#changing the name of the column so it could merge
stadiums.rename(columns={"Host City":"City"}, inplace=True)

In [38]:
#changing the name of the column so it could merge
stadiums.rename(columns={"Official FIFA Stadium Designation":"Venue"}, inplace=True)

In [39]:
stadiums.head(3)

,Host Country,City,Venue,Net Capacity
0,United States,New York/New Jersey,New York New Jersey Stadium,78576
1,United States,Kansas City,Kansas City Stadium,67513
2,United States,San Francisco Bay Area,San Francisco Bay Area Stadium,69391

In [40]:
df_geo = df_geo.merge(
    stadiums[["City", "Host Country"]],
    on="City",
    how="left"
)

In [41]:
df_geo.head(3)

                 Venue         City Host Country
0  Mexico City Stadium  Mexico City       Mexico
1  Estadio Guadalajara  Guadalajara       Mexico
2      Toronto Stadium      Toronto       Canada

## geocoding

In [43]:
df_geo[df_geo["Venue"] == "New York New Jersey Stadium"]
#it didn't put the country in those rows for some reason

                           Venue         City Host Country
5    New York New Jersey Stadium  New York/NJ          NaN
16   New York New Jersey Stadium  New York/NJ          NaN
40   New York New Jersey Stadium  New York/NJ          NaN
55   New York New Jersey Stadium  New York/NJ          NaN
66   New York New Jersey Stadium  New York/NJ          NaN
77   New York New Jersey Stadium  New York/NJ          NaN
92   New York New Jersey Stadium  New York/NJ          NaN
109  New York New Jersey Stadium  New York/NJ          NaN

In [44]:
df_geo.loc[df_geo["Venue"] == "New York New Jersey Stadium",
    "Host Country"
] = "United States"
#.loc is the standard pandas way to select rows and columns by their labels and modify values
#.loc uses that Boolean Series to identify which rows to update

In [45]:
df_geo[df_geo["Venue"] == "New York New Jersey Stadium"]
#checking if it worked

                           Venue         City   Host Country
5    New York New Jersey Stadium  New York/NJ  United States
16   New York New Jersey Stadium  New York/NJ  United States
40   New York New Jersey Stadium  New York/NJ  United States
55   New York New Jersey Stadium  New York/NJ  United States
66   New York New Jersey Stadium  New York/NJ  United States
77   New York New Jersey Stadium  New York/NJ  United States
92   New York New Jersey Stadium  New York/NJ  United States
109  New York New Jersey Stadium  New York/NJ  United States

In [46]:
df_geo.to_csv("df_geo.csv", index=False)

In [47]:
#getting the latitude and longitude
for index, row in df_geo.iterrows():
    full_address = f"{row['Venue']}, {row['City']}, {row['Host Country']}"
    print(full_address)
    
    geo = geocoder.google(full_address, key=api_key_geocoder)
    print("Status:", geo.status)
    print("OK:", geo.ok)
    print("LatLng:", geo.latlng)
    
    if geo.ok:
        df_geo.loc[index, "lat"] = geo.latlng[0]
        df_geo.loc[index, "long"] = geo.latlng[1]
    else:
        print(f"Failed for {full_address}: {geo.status}")

df_geo

Mexico City Stadium, Mexico City, Mexico
Status: OK
OK: True
LatLng: [19.3028607, -99.1505277]
Estadio Guadalajara, Guadalajara, Mexico
Status: OK
OK: True
LatLng: [20.6817764, -103.4626455]
Toronto Stadium, Toronto, Canada
Status: OK
OK: True
LatLng: [43.6331948, -79.41856349999999]
Los Angeles Stadium, Los Angeles, United States
Status: OK
OK: True
LatLng: [33.9534765, -118.3390235]
San Francisco Bay Area Stadium, San Francisco Bay Area, United States
Status: OK
OK: True
LatLng: [37.4033165, -121.9693774]
New York New Jersey Stadium, New York/NJ, United States
Status: OK
OK: True
LatLng: [40.8135064, -74.074457]
Boston Stadium, Boston, United States
Status: OK
OK: True
LatLng: [42.09092740000001, -71.264363]
BC Place Vancouver, Vancouver, Canada
Status: OK
OK: True
LatLng: [49.2827291, -123.1207375]
Houston Stadium, Houston, United States
Status: OK
OK: True
LatLng: [29.6847219, -95.41070739999999]
Dallas Stadium, Dallas, United States
Status: OK
OK: True
LatLng: [32.7480281, -97.09281240000001]
Philadelphia Stadium, Philadelphia, United States
Status: OK
OK: True
LatLng: [39.9014189, -75.1675992]
Estadio Monterrey, Monterrey, Mexico
Status: OK
OK: True
LatLng: [25.7181121, -100.3154111]
Atlanta Stadium, Atlanta, United States
Status: OK
OK: True
LatLng: [33.7553232, -84.40059049999999]
Seattle Stadium, Seattle, United States
Status: OK
OK: True
LatLng: [47.5951518, -122.3316394]
Miami Stadium, Miami, United States
Status: OK
OK: True
LatLng: [25.7616798, -80.1917902]
Los Angeles Stadium, Los Angeles, United States
Status: OK
OK: True
LatLng: [33.9534765, -118.3390235]
New York New Jersey Stadium, New York/NJ, United States
Status: OK
OK: True
LatLng: [40.8135064, -74.074457]
Boston Stadium, Boston, United States
Status: OK
OK: True
LatLng: [42.09092740000001, -71.264363]
Kansas City Stadium, Kansas City, United States
Status: OK
OK: True
LatLng: [39.0489647, -94.4840141]
San Francisco Bay Area Stadium, San Francisco Bay Area, United States
Status: OK
OK: True
LatLng: [37.4033165, -121.9693774]
Houston Stadium, Houston, United States
Status: OK
OK: True
LatLng: [29.6847219, -95.41070739999999]
Dallas Stadium, Dallas, United States
Status: OK
OK: True
LatLng: [32.7480281, -97.09281240000001]
Toronto Stadium, Toronto, Canada
Status: OK
OK: True
LatLng: [43.6331948, -79.41856349999999]
Mexico City Stadium, Mexico City, Mexico
Status: OK
OK: True
LatLng: [19.3028607, -99.1505277]
Atlanta Stadium, Atlanta, United States
Status: OK
OK: True
LatLng: [33.7553232, -84.40059049999999]
Los Angeles Stadium, Los Angeles, United States
Status: OK
OK: True
LatLng: [33.9534765, -118.3390235]
BC Place Vancouver, Vancouver, Canada
Status: OK
OK: True
LatLng: [49.2827291, -123.1207375]
Estadio Guadalajara, Guadalajara, Mexico
Status: OK
OK: True
LatLng: [20.6817764, -103.4626455]
Seattle Stadium, Seattle, United States
Status: OK
OK: True
LatLng: [47.5951518, -122.3316394]
Boston Stadium, Boston, United States
Status: OK
OK: True
LatLng: [42.09092740000001, -71.264363]
Philadelphia Stadium, Philadelphia, United States
Status: OK
OK: True
LatLng: [39.9014189, -75.1675992]
San Francisco Bay Area Stadium, San Francisco Bay Area, United States
Status: OK
OK: True
LatLng: [37.4033165, -121.9693774]
Houston Stadium, Houston, United States
Status: OK
OK: True
LatLng: [29.6847219, -95.41070739999999]
Toronto Stadium, Toronto, Canada
Status: OK
OK: True
LatLng: [43.6331948, -79.41856349999999]
Kansas City Stadium, Kansas City, United States
Status: OK
OK: True
LatLng: [39.0489647, -94.4840141]
Estadio Monterrey, Monterrey, Mexico
Status: OK
OK: True
LatLng: [25.7181121, -100.3154111]
Atlanta Stadium, Atlanta, United States
Status: OK
OK: True
LatLng: [33.7553232, -84.40059049999999]
Los Angeles Stadium, Los Angeles, United States
Status: OK
OK: True
LatLng: [33.9534765, -118.3390235]
Miami Stadium, Miami, United States
Status: OK
OK: True
LatLng: [25.7616798, -80.1917902]
BC Place Vancouver, Vancouver, Canada
Status: OK
OK: True
LatLng: [49.2827291, -123.1207375]
New York New Jersey Stadium, New York/NJ, United States
Status: OK
OK: True
LatLng: [40.8135064, -74.074457]
Philadelphia Stadium, Philadelphia, United States
Status: OK
OK: True
LatLng: [39.9014189, -75.1675992]
Dallas Stadium, Dallas, United States
Status: OK
OK: True
LatLng: [32.7480281, -97.09281240000001]
San Francisco Bay Area Stadium, San Francisco Bay Area, United States
Status: OK
OK: True
LatLng: [37.4033165, -121.9693774]
Boston Stadium, Boston, United States
Status: OK
OK: True
LatLng: [42.09092740000001, -71.264363]
Toronto Stadium, Toronto, Canada
Status: OK
OK: True
LatLng: [43.6331948, -79.41856349999999]
Houston Stadium, Houston, United States
Status: OK
OK: True
LatLng: [29.6847219, -95.41070739999999]
Estadio Guadalajara, Guadalajara, Mexico
Status: OK
OK: True
LatLng: [20.6817764, -103.4626455]
Miami Stadium, Miami, United States
Status: OK
OK: True
LatLng: [25.7616798, -80.1917902]
Atlanta Stadium, Atlanta, United States
Status: OK
OK: True
LatLng: [33.7553232, -84.40059049999999]
BC Place Vancouver, Vancouver, Canada
Status: OK
OK: True
LatLng: [49.2827291, -123.1207375]
Seattle Stadium, Seattle, United States
Status: OK
OK: True
LatLng: [47.5951518, -122.3316394]
Mexico City Stadium, Mexico City, Mexico
Status: OK
OK: True
LatLng: [19.3028607, -99.1505277]
Estadio Monterrey, Monterrey, Mexico
Status: OK
OK: True
LatLng: [25.7181121, -100.3154111]
Philadelphia Stadium, Philadelphia, United States
Status: OK
OK: True
LatLng: [39.9014189, -75.1675992]
New York New Jersey Stadium, New York/NJ, United States
Status: OK
OK: True
LatLng: [40.8135064, -74.074457]
Dallas Stadium, Dallas, United States
Status: OK
OK: True
LatLng: [32.7480281, -97.09281240000001]
Kansas City Stadium, Kansas City, United States
Status: OK
OK: True
LatLng: [39.0489647, -94.4840141]
Los Angeles Stadium, Los Angeles, United States
Status: OK
OK: True
LatLng: [33.9534765, -118.3390235]
San Francisco Bay Area Stadium, San Francisco Bay Area, United States
Status: OK
OK: True
LatLng: [37.4033165, -121.9693774]
Seattle Stadium, Seattle, United States
Status: OK
OK: True
LatLng: [47.5951518, -122.3316394]
BC Place Vancouver, Vancouver, Canada
Status: OK
OK: True
LatLng: [49.2827291, -123.1207375]
Mexico City Stadium, Mexico City, Mexico
Status: OK
OK: True
LatLng: [19.3028607, -99.1505277]
Estadio Guadalajara, Guadalajara, Mexico
Status: OK
OK: True
LatLng: [20.6817764, -103.4626455]
Boston Stadium, Boston, United States
Status: OK
OK: True
LatLng: [42.09092740000001, -71.264363]
Miami Stadium, Miami, United States
Status: OK
OK: True
LatLng: [25.7616798, -80.1917902]
New York New Jersey Stadium, New York/NJ, United States
Status: OK
OK: True
LatLng: [40.8135064, -74.074457]
Philadelphia Stadium, Philadelphia, United States
Status: OK
OK: True
LatLng: [39.9014189, -75.1675992]
Dallas Stadium, Dallas, United States
Status: OK
OK: True
LatLng: [32.7480281, -97.09281240000001]
Kansas City Stadium, Kansas City, United States
Status: OK
OK: True
LatLng: [39.0489647, -94.4840141]
Miami Stadium, Miami, United States
Status: OK
OK: True
LatLng: [25.7616798, -80.1917902]
Atlanta Stadium, Atlanta, United States
Status: OK
OK: True
LatLng: [33.7553232, -84.40059049999999]
ROUND OF 32 (June 28 – July 3, 2026), ROUND OF 32 (June 28 – July 3, 2026), nan
Status: ZERO_RESULTS
OK: False
LatLng: None
Failed for ROUND OF 32 (June 28 – July 3, 2026), ROUND OF 32 (June 28 – July 3, 2026), nan: ZERO_RESULTS
Los Angeles Stadium, Los Angeles, United States
Status: OK
OK: True
LatLng: [33.9534765, -118.3390235]
Boston Stadium, Boston, United States
Status: OK
OK: True
LatLng: [42.09092740000001, -71.264363]
Estadio Monterrey, Monterrey, Mexico
Status: OK
OK: True
LatLng: [25.7181121, -100.3154111]
Houston Stadium, Houston, United States
Status: OK
OK: True
LatLng: [29.6847219, -95.41070739999999]
New York New Jersey Stadium, New York/NJ, United States
Status: OK
OK: True
LatLng: [40.8135064, -74.074457]
Dallas Stadium, Dallas, United States
Status: OK
OK: True
LatLng: [32.7480281, -97.09281240000001]
Mexico City Stadium, Mexico City, Mexico
Status: OK
OK: True
LatLng: [19.3028607, -99.1505277]
Atlanta Stadium, Atlanta, United States
Status: OK
OK: True
LatLng: [33.7553232, -84.40059049999999]
San Francisco Bay Area Stadium, San Francisco Bay Area, United States
Status: OK
OK: True
LatLng: [37.4033165, -121.9693774]
Seattle Stadium, Seattle, United States
Status: OK
OK: True
LatLng: [47.5951518, -122.3316394]
Toronto Stadium, Toronto, Canada
Status: OK
OK: True
LatLng: [43.6331948, -79.41856349999999]
Los Angeles Stadium, Los Angeles, United States
Status: OK
OK: True
LatLng: [33.9534765, -118.3390235]
BC Place Vancouver, Vancouver, Canada
Status: OK
OK: True
LatLng: [49.2827291, -123.1207375]
Miami Stadium, Miami, United States
Status: OK
OK: True
LatLng: [25.7616798, -80.1917902]
Kansas City Stadium, Kansas City, United States
Status: OK
OK: True
LatLng: [39.0489647, -94.4840141]
Dallas Stadium, Dallas, United States
Status: OK
OK: True
LatLng: [32.7480281, -97.09281240000001]
ROUND OF 16 (July 4 – July 7, 2026), ROUND OF 16 (July 4 – July 7, 2026), nan
Status: ZERO_RESULTS
OK: False
LatLng: None
Failed for ROUND OF 16 (July 4 – July 7, 2026), ROUND OF 16 (July 4 – July 7, 2026), nan: ZERO_RESULTS
Philadelphia Stadium, Philadelphia, United States
Status: OK
OK: True
LatLng: [39.9014189, -75.1675992]
Houston Stadium, Houston, United States
Status: OK
OK: True
LatLng: [29.6847219, -95.41070739999999]
New York New Jersey Stadium, New York/NJ, United States
Status: OK
OK: True
LatLng: [40.8135064, -74.074457]
Mexico City Stadium, Mexico City, Mexico
Status: OK
OK: True
LatLng: [19.3028607, -99.1505277]
Dallas Stadium, Dallas, United States
Status: OK
OK: True
LatLng: [32.7480281, -97.09281240000001]
Seattle Stadium, Seattle, United States
Status: OK
OK: True
LatLng: [47.5951518, -122.3316394]
Atlanta Stadium, Atlanta, United States
Status: OK
OK: True
LatLng: [33.7553232, -84.40059049999999]
BC Place Vancouver, Vancouver, Canada
Status: OK
OK: True
LatLng: [49.2827291, -123.1207375]
QUARTER-FINALS (July 9 – July 11, 2026), QUARTER-FINALS (July 9 – July 11, 2026), nan
Status: ZERO_RESULTS
OK: False
LatLng: None
Failed for QUARTER-FINALS (July 9 – July 11, 2026), QUARTER-FINALS (July 9 – July 11, 2026), nan: ZERO_RESULTS
Boston Stadium, Boston, United States
Status: OK
OK: True
LatLng: [42.09092740000001, -71.264363]
Los Angeles Stadium, Los Angeles, United States
Status: OK
OK: True
LatLng: [33.9534765, -118.3390235]
Miami Stadium, Miami, United States
Status: OK
OK: True
LatLng: [25.7616798, -80.1917902]
Kansas City Stadium, Kansas City, United States
Status: OK
OK: True
LatLng: [39.0489647, -94.4840141]
SEMI-FINALS (July 14 – July 15, 2026), SEMI-FINALS (July 14 – July 15, 2026), nan
Status: ZERO_RESULTS
OK: False
LatLng: None
Failed for SEMI-FINALS (July 14 – July 15, 2026), SEMI-FINALS (July 14 – July 15, 2026), nan: ZERO_RESULTS
Dallas Stadium, Dallas, United States
Status: OK
OK: True
LatLng: [32.7480281, -97.09281240000001]
Atlanta Stadium, Atlanta, United States
Status: OK
OK: True
LatLng: [33.7553232, -84.40059049999999]
THIRD-PLACE MATCH (July 18, 2026), THIRD-PLACE MATCH (July 18, 2026), nan
Status: OK
OK: True
LatLng: [18.6848086, 100.8000051]
Miami Stadium, Miami, United States
Status: OK
OK: True
LatLng: [25.7616798, -80.1917902]
FINAL (July 19, 2026), FINAL (July 19, 2026), nan
Status: ZERO_RESULTS
OK: False
LatLng: None
Failed for FINAL (July 19, 2026), FINAL (July 19, 2026), nan: ZERO_RESULTS
New York New Jersey Stadium, New York/NJ, United States
Status: OK
OK: True
LatLng: [40.8135064, -74.074457]

,Venue,City,Host Country,lat,long
0,Mexico City Stadium,Mexico City,Mexico,19.302861,-99.150528
1,Estadio Guadalajara,Guadalajara,Mexico,20.681776,-103.462645
2,Toronto Stadium,Toronto,Canada,43.633195,-79.418563
3,Los Angeles Stadium,Los Angeles,United States,33.953477,-118.339023
4,San Francisco Bay Area Stadium,San Francisco Bay Area,United States,37.403317,-121.969377
...,...,...,...,...,...
105,Atlanta Stadium,Atlanta,United States,33.755323,-84.400590
106,"THIRD-PLACE MATCH (July 18, 2026)","THIRD-PLACE MATCH (July 18, 2026)",NaN,18.684809,100.800005
107,Miami Stadium,Miami,United States,25.761680,-80.191790
108,"FINAL (July 19, 2026)","FINAL (July 19, 2026)",NaN,NaN,NaN
109,New York New Jersey Stadium,New York/NJ,United States,40.813506,-74.074457

In [48]:
df_geo.to_csv("df_geo.csv", index=False)

## doing some analysis

In [49]:
matches.head()

,Match,Date,Team 1,Team 2,Venue,City,phase
1,1,2026-06-11,Mexico,South Africa,Mexico City Stadium,Mexico City,Group Stage
2,2,2026-06-11,South Korea,Czech Republic,Estadio Guadalajara,Guadalajara,Group Stage
3,3,2026-06-12,Canada,Bosnia and Herzegovina,Toronto Stadium,Toronto,Group Stage
4,4,2026-06-12,USA,Paraguay,Los Angeles Stadium,Los Angeles,Group Stage
5,5,2026-06-13,Qatar,Switzerland,San Francisco Bay Area Stadium,San Francisco Bay Area,Group Stage

In [50]:
matches_by_city = matches["City"].value_counts()
matches_by_city
#Dallas hosted more games

City
Dallas                                     9
Los Angeles                                8
New York/NJ                                8
Atlanta                                    8
Miami                                      8
Boston                                     7
Vancouver                                  7
Mexico City                                6
San Francisco Bay Area                     6
Houston                                    6
Philadelphia                               6
Seattle                                    6
Kansas City                                6
Toronto                                    5
Guadalajara                                4
Monterrey                                  4
ROUND OF 32 (June 28 – July 3, 2026)       1
ROUND OF 16 (July 4 – July 7, 2026)        1
QUARTER-FINALS (July 9 – July 11, 2026)    1
SEMI-FINALS (July 14 – July 15, 2026)      1
THIRD-PLACE MATCH (July 18, 2026)          1
FINAL (July 19, 2026)                      1
Name: count, dtype: int64

In [51]:
stadiums = matches["Venue"].value_counts()
stadiums

Venue
Dallas Stadium                             9
Los Angeles Stadium                        8
New York New Jersey Stadium                8
Atlanta Stadium                            8
Miami Stadium                              8
Boston Stadium                             7
BC Place Vancouver                         7
Mexico City Stadium                        6
San Francisco Bay Area Stadium             6
Houston Stadium                            6
Philadelphia Stadium                       6
Seattle Stadium                            6
Kansas City Stadium                        6
Toronto Stadium                            5
Estadio Guadalajara                        4
Estadio Monterrey                          4
ROUND OF 32 (June 28 – July 3, 2026)       1
ROUND OF 16 (July 4 – July 7, 2026)        1
QUARTER-FINALS (July 9 – July 11, 2026)    1
SEMI-FINALS (July 14 – July 15, 2026)      1
THIRD-PLACE MATCH (July 18, 2026)          1
FINAL (July 19, 2026)                      1
Name: count, dtype: int64

In [52]:
#I decided that i'm working with the first week of the world cup
group_stage = matches[matches["phase"] == "Group Stage"]
group_stage

,Match,Date,Team 1,Team 2,Venue,City,phase
1,1,2026-06-11,Mexico,South Africa,Mexico City Stadium,Mexico City,Group Stage
2,2,2026-06-11,South Korea,Czech Republic,Estadio Guadalajara,Guadalajara,Group Stage
3,3,2026-06-12,Canada,Bosnia and Herzegovina,Toronto Stadium,Toronto,Group Stage
4,4,2026-06-12,USA,Paraguay,Los Angeles Stadium,Los Angeles,Group Stage
5,5,2026-06-13,Qatar,Switzerland,San Francisco Bay Area Stadium,San Francisco Bay Area,Group Stage
...,...,...,...,...,...,...,...
68,68,2026-06-27,Croatia,Ghana,Philadelphia Stadium,Philadelphia,Group Stage
69,69,2026-06-27,Jordan,Argentina,Dallas Stadium,Dallas,Group Stage
70,70,2026-06-27,Algeria,Austria,Kansas City Stadium,Kansas City,Group Stage
71,71,2026-06-27,Colombia,Portugal,Miami Stadium,Miami,Group Stage
72,72,2026-06-27,DR Congo,Uzbekistan,Atlanta Stadium,Atlanta,Group Stage

In [53]:
group_stage.drop(columns="phase")

,Match,Date,Team 1,Team 2,Venue,City
1,1,2026-06-11,Mexico,South Africa,Mexico City Stadium,Mexico City
2,2,2026-06-11,South Korea,Czech Republic,Estadio Guadalajara,Guadalajara
3,3,2026-06-12,Canada,Bosnia and Herzegovina,Toronto Stadium,Toronto
4,4,2026-06-12,USA,Paraguay,Los Angeles Stadium,Los Angeles
5,5,2026-06-13,Qatar,Switzerland,San Francisco Bay Area Stadium,San Francisco Bay Area
...,...,...,...,...,...,...
68,68,2026-06-27,Croatia,Ghana,Philadelphia Stadium,Philadelphia
69,69,2026-06-27,Jordan,Argentina,Dallas Stadium,Dallas
70,70,2026-06-27,Algeria,Austria,Kansas City Stadium,Kansas City
71,71,2026-06-27,Colombia,Portugal,Miami Stadium,Miami
72,72,2026-06-27,DR Congo,Uzbekistan,Atlanta Stadium,Atlanta

In [54]:
matches.groupby("Date")["Match"].count().sort_values(ascending=False)
#number of games per day during the whole world cup

Date
2026-06-26    6
2026-06-25    6
2026-06-27    6
2026-06-24    6
2026-06-20    4
2026-06-19    4
2026-06-13    4
2026-06-14    4
2026-06-15    4
2026-06-16    4
2026-06-23    4
2026-06-22    4
2026-06-18    4
2026-06-17    4
2026-06-21    4
2026-06-30    3
2026-07-03    3
2026-06-29    3
2026-07-01    3
2026-07-02    3
2026-06-12    2
2026-06-11    2
2026-07-07    2
2026-07-04    2
2026-07-05    2
2026-07-06    2
2026-07-11    2
2026-06-28    1
2026-07-09    1
2026-07-10    1
2026-07-14    1
2026-07-15    1
2026-07-18    1
2026-07-19    1
Name: Match, dtype: int64

In [55]:
group_stage.groupby("Date")["Match"].count().sort_values(ascending=False)
#number of games per day during the group phase

Date
2026-06-24    6
2026-06-26    6
2026-06-25    6
2026-06-27    6
2026-06-23    4
2026-06-13    4
2026-06-14    4
2026-06-15    4
2026-06-16    4
2026-06-21    4
2026-06-19    4
2026-06-17    4
2026-06-18    4
2026-06-20    4
2026-06-22    4
2026-06-11    2
2026-06-12    2
Name: Match, dtype: int64

## getting data from the Air traffic (OPenSky)

In [56]:
group_stage.groupby("Date")['Match'].count()

Date
2026-06-11    2
2026-06-12    2
2026-06-13    4
2026-06-14    4
2026-06-15    4
2026-06-16    4
2026-06-17    4
2026-06-18    4
2026-06-19    4
2026-06-20    4
2026-06-21    4
2026-06-22    4
2026-06-23    4
2026-06-24    6
2026-06-25    6
2026-06-26    6
2026-06-27    6
Name: Match, dtype: int64

In [57]:
#first day of the world cup 
group_stage[["Date", "City"]].head(2)

        Date         City
1 2026-06-11  Mexico City
2 2026-06-11  Guadalajara

In [58]:
airports_mexico_city = {"airport_1" : "Benito Juárez International Airport (MEX)",
                        "ICAO_code_1" : "MMMX",
                        "airport_2" : "Felipe Ángeles International Airport (AIFA)",
                        "ICAO_code_2" : "MMSM"}

In [59]:
airports_mexico_city.keys()

dict_keys(['airport_1', 'ICAO_code_1', 'airport_2', 'ICAO_code_2'])

In [60]:
airports_guadalajara = {"airport": "Guadalajara International Airport",
                        "ICAO_code": "MMGL"}

In [86]:
#begin and end are not dates or ISO timestamps
#must be Unix timestamps (seconds since January 1, 1970 UTC)

#From June 10 at 00h to June 11 at 10am in NY
#first game started at 15h June 11

begin = int(datetime(2026, 6, 10, 0, 0, tzinfo=timezone.utc).timestamp())
end = int(datetime(2026, 6, 10, 1, 0, tzinfo=timezone.utc).timestamp())

print(begin)
print(end)

1781049600
1781053200

In [87]:
with OpenSkyApi(token_manager=TokenManager.from_json_file("credentials.json")) as api:
    states = api.get_states()

In [89]:
api = OpenSkyApi()
arrivals = api.get_arrivals_by_airport("KJFK", begin, end)
print(arrivals)
#didn't work with the library

None

In [79]:
#example from the website
api = OpenSkyApi()
arrivals = api.get_arrivals_by_airport("EDDF", 1517227200, 1517230800)
print("Arrivals:")
for flight in arrivals:
    print(flight)

Arrivals:

TypeError: 'NoneType' object is not iterable

In [81]:
print(arrivals)
print(type(arrivals))

None
<class 'NoneType'>

In [82]:
if arrivals:
    for flight in arrivals:
        print(flight.callsign)
else:
    print("No flights returned")

No flights returned

In [74]:
#test2
api = OpenSkyApi()
states = api.get_states()
for s in states.states:
    print("(%r, %r, %r, %r)" % (s.longitude, s.latitude, s.baro_altitude, s.velocity))

(12.4039, 37.9645, 11582.4, 227.93)
(-7.2917, 39.1197, 11277.6, 227.42)
(-77.2215, 41.9609, 10957.56, 218.22)
(-81.6979, 27.6458, 762, 38.92)
(24.3144, 39.8427, 11590.02, 213.05)
(18.8428, 36.494, 11285.22, 245.13)
(3.6231, 46.9774, 10340.34, 234.3)
(49.0422, 26.7642, 12192, 257.23)
(20.8603, 52.5928, 419.1, 40.04)
(-82.7917, 34.5309, 4213.86, 168.41)
(2.3618, 48.4698, 1493.52, 147.33)
(14.5324, 54.642, 2903.22, 63.28)
(76.7408, 26.8158, 6012.18, 199.09)
(106.4843, -6.0837, 1272.54, 107.28)
(7.0117, 50.7101, 11894.82, 233.89)
(-0.9844, 43.8617, 11887.2, 222.67)
(131.3211, 33.4127, 6400.8, 228.96)
(-122.3647, 47.6035, 381, 61.77)
(-78.4915, 34.4671, 2987.04, 159.53)
(77.264, 12.1938, 8229.6, 190.55)
(-77.0363, 38.7886, 708.66, 108.03)
(28.1522, -26.0225, 3268.98, 129.76)
(-105.1202, 40.0494, 2225.04, 66.27)
(-75.2342, 39.8778, None, 5.66)
(-129.5408, 43.669, 11277.6, 235.94)
(-80.9911, 38.5384, 11582.4, 215.78)
(76.8411, 27.6506, 6103.62, 204.84)
(-73.4035, 45.5182, None, 0)
(76.9919, 14.197, 8938.26, 215.83)
(140.048, 37.5863, 10363.2, 240.9)
(-75.7294, 37.7207, 11582.4, 220.25)
(-98.5268, 31.7312, 4549.14, 107.46)
(2.3678, 48.7245, None, 0)
(23.7748, 35.2846, 6629.4, 205.17)
(-12.3334, 38.4467, 11574.78, 235.36)
(-95.4669, 30.5013, 5509.26, 193.61)
(-12.4098, 30.4626, 11277.6, 217.3)
(76.5553, 26.4723, 8732.52, 230.04)
(107.0046, -6.0822, 3192.78, 152.18)
(2.4459, 48.7351, 746.76, 78.51)
(-4.4431, 40.0276, 11887.2, 231.77)
(21.4645, 41.0393, 9646.92, 204.91)
(6.3405, 46.707, 10363.2, 243.35)
(25.3217, 35.9452, 4069.08, 150.46)
(-1.7257, 48.0689, None, 0)
(17.5427, 45.1311, 11582.4, 193.34)
(-116.3084, 32.9877, 9258.3, 234.78)
(-95.4773, 41.2734, 10363.2, 225.89)
(3.3099, 49.8819, 10668, 227.67)
(-88.2331, 36.2694, 11574.78, 238.19)
(1.7903, 48.3803, 10972.8, 242.46)
(16.5976, 58.2286, 10347.96, 201.48)
(88.6136, 26.3501, 10972.8, 249.74)
(-73.8594, 40.772, None, 0.39)
(5.3206, 48.1374, 10363.2, 250.92)
(24.6162, 39.0241, 11597.64, 216.95)
(36.9163, 36.1774, 9753.6, 248.68)
(11.9267, 49.4474, 10050.78, 263.11)
(26.1634, 43.1649, 10629.9, 220.96)
(88.6215, 22.8467, 2918.46, 105.6)
(20.0086, 46.9501, 11582.4, 206.48)
(31.9091, 39.8405, 10363.2, 224.95)
(-74.1202, 4.6891, 2628.9, 95.38)
(-4.6227, 36.667, 6705.6, 145.68)
(13.6273, 54.7473, 1981.2, 58.07)
(77.5046, 28.5082, 1866.9, 87.89)
(4.6597, 45.7345, 11277.6, 235.63)
(-9.2071, 37.0291, 13106.4, 230.29)
(-56.2788, -13.326, 403.86, 68.77)
(17.9287, 47.215, 11582.4, 190.44)
(-75.4828, 40.3472, 1371.6, 137.65)
(27.9548, 42.0742, 10363.2, 228.22)
(10.008, 54.1404, 548.64, 52.03)
(-2.2843, 53.3678, None, 1.8)
(4.7039, 50.5844, 2217.42, 142.31)
(13.1409, 47.8271, 10668, 256.71)
(36.6951, 36.6682, 10370.82, 228.5)
(70.5576, 20.28, 13106.4, 258.61)
(-82.3308, 27.1945, 929.64, 25.8)
(-3.8562, 36.2761, 3657.6, 110.19)
(77.1239, 28.5382, 480.06, 75.62)
(-82.3443, 38.1879, 11582.4, 213.83)
(-74.1741, 40.6898, None, 2.06)
(-80.0525, 32.872, 91.44, 54.11)
(72.9093, 19.0893, 251.46, 64.31)
(22.0745, 41.8829, 10683.24, 264.11)
(-104.6622, 39.8685, None, 99.3)
(23.4378, 37.3542, 2209.8, 130.3)
(13.2638, 46.1282, 10972.8, 205.3)
(-78.1114, -10.0368, 10668, 232.96)
(78.3177, 28.0885, 4922.52, 200.37)
(-94.3976, 32.3774, 11582.4, 180.23)
(-80.1213, 26.2615, 7.62, 41.78)
(72.8638, 19.0887, None, 47.33)
(28.8792, -26.5231, 6743.7, 224.5)
(-62.4956, -29.4719, 10965.18, 206.46)
(-64.2362, 43.4748, 12192, 233.48)
(5.4326, 44.1288, 10668, 227.77)
(-81.1249, 29.3599, 1310.64, 56.45)
(-4.8117, 43.1227, 10972.8, 237.67)
(-89.1593, 42.4428, 5722.62, 222.01)
(4.5497, 49.3494, 10683.24, 236.75)
(4.7116, 52.9221, 274.32, 52.89)
(-79.552, 42.2022, 9715.5, 254.34)
(-80.7562, 27.6739, 1318.26, 48.55)
(-76.95, 33.9238, 12496.8, 262.06)
(-77.7534, 39.2342, 7924.8, 221.1)
(17.0552, 49.1606, 9563.1, 239.6)
(-89.1589, 36.3398, 8229.6, 225.18)
(-92.0842, 31.1642, 11277.6, 242.26)
(0.6405, 43.5086, 9745.98, 237.43)
(-85.1927, 36.207, 11887.2, 229.28)
(10.0568, 59.9087, 4495.8, 162.43)
(11.1901, 60.5632, 5958.84, 178.29)
(-87.8388, 41.9658, 434.34, 62.25)
(-84.4318, 34.3044, 487.68, 36.79)
(-81.3145, 28.414, None, 0.06)
(-112.5348, 41.0719, 2537.46, 56.23)
(-61.8798, -30.8822, 11277.6, 251.6)
(-49.5286, -20.639, 12184.38, 217.9)
(-6.4492, 39.5568, 9250.68, 245.33)
(-83.7003, 34.6586, 6461.76, 221.38)
(128.2541, 27.3434, 6918.96, 224.04)
(10.0926, 42.3757, 11887.2, 230.74)
(-8.2097, 41.0689, 2796.54, 148.46)
(-1.7174, 40.52, 8831.58, 211.96)
(3.3279, 46.0953, 10058.4, 216.91)
(19.5533, 46.9445, 11277.6, 280.72)
(-58.4207, -35.0926, 1524, 124.65)
(-3.6301, 40.1538, 2499.36, 134.7)
(1.155, 48.2405, 4511.04, 207.52)
(4.8899, 55.4983, 11894.82, 239.07)
(-71.6389, 41.3168, 2430.78, 52.23)
(-2.2432, 52.7819, 6278.88, 177.53)
(-82.3184, 29.3593, 1310.64, 36.1)
(4.0047, 47.8076, 6027.42, 210.61)
(-54.8491, -13.9801, 11582.4, 203.9)
(-67.3468, -1.927, 12192, 208.32)
(12.4642, 49.4416, 11582.4, 193.96)
(-59.2214, -33.571, 7856.22, 206.67)
(-81.2317, 29.9454, 8107.68, 239.2)
(15.125, 51.9545, 8496.3, 268.59)
(-97.4287, 37.6341, 693.42, 23.86)
(17.4306, 47.9667, 6583.68, 227.33)
(-2.6707, 41.2794, 10668, 228.76)
(77.4623, 13.2866, 3291.84, 148.5)
(21.825, 46.1239, 11582.4, 205.55)
(28.7498, 43.4904, 11590.02, 238.82)
(-72.0418, 40.7315, 7368.54, 258.48)
(-47.0686, -25.0981, 8724.9, 213.88)
(13.7839, 50.8932, 11887.2, 192.1)
(-122.2999, 47.4479, None, 0.64)
(7.2165, 43.6639, None, 0)
(23.9512, 37.9376, None, 0)
(16.9698, 42.5011, 10980.42, 209.53)
(13.5136, 39.7347, 10660.38, 241.93)
(16.1588, 40.8999, 11269.98, 245.43)
(3.6787, 40.0366, 11582.4, 233.39)
(2.8226, 51.4615, 10972.8, 214.19)
(26.6527, 42.775, 10370.82, 221.34)
(-0.7199, 51.8289, 3703.32, 143.98)
(-10.1355, 53.9533, 9753.6, 239.89)
(-0.7117, 51.824, 3665.22, 140.44)
(-76.8924, 34.2315, 11277.6, 241.53)
(-7.5421, 41.3689, 8229.6, 231.6)
(1.9298, 52.0996, 10058.4, 227.14)
(-78.6128, 37.8935, 1623.06, 131.43)
(7.2342, 50.8078, 434.34, 66.62)
(12.6454, 55.6228, None, 5.66)
(-7.7167, 56.598, 10027.92, 234.59)
(12.5436, 48.9264, 1066.8, 42.82)
(13.0342, 47.878, 1478.28, 56.09)
(22.4154, 38.0448, 9845.04, 251.35)
(23.7101, 37.7012, 1645.92, 131.6)
(13.2178, 47.1172, 10675.62, 254.52)
(133.2202, 34.6863, 5021.58, 205.01)
(22.5323, 38.0189, 7589.52, 229.09)
(-93.2095, 44.8854, None, 0.06)
(19.4485, 39.8599, 10972.8, 216.38)
(23.9518, 37.9423, None, 0)
(-78.558, 36.8657, 9448.8, 222.97)
(-82.0546, 30.0541, 975.36, 59.64)
(-76.0118, 37.137, 762, 56)
(1.3494, 43.6344, None, 0)
(-90.4452, 35.9985, 731.52, 62.72)
(101.7595, 11.1895, 9753.6, 238.77)
(-91.594, 36.1338, 11887.2, 201.16)
(11.8928, 48.1926, 10668, 259.02)
(-93.9313, 41.2457, 3482.34, 183.84)
(0.2894, 51.1895, 5097.78, 196.2)
(24.1502, 38.2022, 5181.6, 180.21)
(23.9497, 37.936, None, 0)
(23.5319, 38.7357, 6690.36, 233.78)
(0.301, 41.3455, 10370.82, 238.74)
(15.0444, 46.6512, 10668, 273.57)
(-82.1682, 27.7315, 868.68, 47.87)
(16.4857, 41.3897, 12496.8, 209.99)
(4.0461, 44.8385, 11582.4, 230.04)
(None, None, None, 234.64)
(6.388, 56.6879, 11887.2, 236.23)
(139.7144, 39.4189, 11582.4, 222.01)
(-91.2712, 44.1492, 9639.3, 264.46)
(23.6247, 37.5867, 2217.42, 137.05)
(27.2647, 42.3811, 1371.6, 109.52)
(10.3493, 60.1728, 3345.18, 181.06)
(8.3185, 57.7616, 10972.8, 227.16)
(-79.3848, 27.9249, 10759.44, 243.03)
(-89.0165, 14.0773, 4640.58, 212.24)
(-69.94, -4.1861, 68.58, 73.28)
(-82.9244, 39.7933, 13716, 234.06)
(-48.6844, -22.8672, 9753.6, 213.12)
(-71.7417, 42.0262, 1066.8, 82.53)
(-81.259, 40.9525, 1150.62, 96.51)
(-96.7908, 32.8308, 10355.58, 232.47)
(14.1326, 51.3132, 243.84, 53.03)
(-4.6082, 36.7332, 541.02, 93.9)
(-93.2422, 44.8873, None, 0.06)
(101.6468, 2.8605, 601.98, 80.05)
(86.7961, 23.3476, 3093.72, 149.03)
(2.0996, 41.293, None, 13.38)
(89.189, 23.0121, 4442.46, 166.12)
(-99.4635, 27.5564, None, 0)
(-37.1329, -2.846, 9761.22, 189.92)
(-77.5621, 39.0886, 152.4, 43.92)
(106.6224, -6.1228, 160.02, 64.49)
(24.956, 60.3176, None, 8.23)
(-89.6914, 34.4365, 10972.8, 242.75)
(-74.9541, 41.2486, 6690.36, 204.19)
(7.8173, 57.1949, 11277.6, 241.74)
(14.1874, 58.3479, 11277.6, 216.49)
(10.4989, 42.3459, 6309.36, 216.45)
(18.0918, 59.3181, 1905, 121.7)
(17.9073, 59.3548, 1242.06, 105.33)
(10.1074, 45.2017, 10972.8, 234.63)
(-61.39, -32.1115, 11887.2, 248.86)
(-64.2109, -31.1524, 1280.16, 84.38)
(-82.8472, 39.9901, 373.38, 58.28)
(-79.5999, 43.6795, None, 6.69)
(141.1346, -34.7292, 10363.2, 237.02)
(-86.6899, 41.4778, 1798.32, 80.34)
(15.2563, 59.2878, 9890.76, 210.38)
(-84.5043, 41.1833, 9448.8, 234.7)
(15.4757, 55.0135, 11277.6, 202.54)
(19.8028, 50.0777, None, 3.6)
(-4.7666, 37.0141, 2590.8, 119.46)
(10.369, 47.275, 3124.2, 72.4)
(-97.7159, 41.1361, 8229.6, 216.7)
(-76.1298, 41.6601, 9006.84, 225.31)
(-85.1014, 34.208, 4838.7, 220.15)
(13.5354, 59.4332, 10012.68, 205.78)
(17.9272, 59.6464, None, 0)
(17.7225, 58.4301, 7475.22, 193.23)
(-90.0931, 41.5431, 11582.4, 197.56)
(10.9043, 61.0215, 3886.2, 222.44)
(-6.1603, 54.6565, 60.96, 38.43)
(71.2416, 23.5076, 9151.62, 248.12)
(-87.5008, 41.9877, 1973.58, 115.75)
(-80.077, 26.67, 213.36, 53.47)
(73.0419, 19.0912, 937.26, 84.38)
(22.2891, 42.0538, 11277.6, 254.33)
(-90.1992, 38.8044, 2537.46, 147.28)
(142.3666, 40.3523, 10363.2, 236.8)
(-5.1845, 35.8047, 11277.6, 221.75)
(137.066, -32.6206, 7315.2, 132.52)
(8.7725, 51.1377, 2438.4, 96.02)
(127.7091, 27.1635, 6416.04, 213.98)
(2.8643, 44.7325, 11277.6, 229.57)
(77.8852, 13.1881, 1661.16, 89.52)
(26.1668, 43.6127, 11582.4, 232.83)
(-2.5072, 40.1539, 9448.8, 243.87)
(1.5656, 39.5938, 9448.8, 224.76)
(77.1093, 11.6837, 10683.24, 230.44)
(9.6657, 48.5424, 10972.8, 211.09)
(-70.6134, 42.1211, 2446.02, 141.7)
(-83.7524, 31.8984, 10660.38, 224.83)
(-66.2087, 18.4888, 678.18, 101.15)
(None, None, None, 104.71)
(-89.3317, 39.286, 8183.88, 215.73)
(-82.2978, 33.7161, 10363.2, 224.61)
(-57.6376, -33.756, 8496.3, 174.52)
(138.983, 34.7238, 6332.22, 220.41)
(28.1381, 42.9803, 10668, 237.15)
(-120.5581, 33.6307, 10187.94, 257.16)
(132.0864, 31.9444, 9113.52, 243.58)
(77.7119, 13.4679, 11887.2, 256.63)
(6.5085, 40.7112, 9448.8, 252.34)
(-82.4166, 27.084, 137.16, 50.97)
(-90.6218, 32.7719, 12496.8, 229.34)
(88.4406, 22.6434, 114.3, 1.03)
(2.7935, 48.4488, 10363.2, 211.49)
(11.8023, 46.4035, 11590.02, 208.66)
(1.4913, 38.9216, 510.54, 88.61)
(21.9712, 45.9844, 10660.38, 271.98)
(7.3082, 40.869, 10370.82, 235.07)
(26.0378, 44.5617, 289.56, 78.17)
(15.2222, 49.4187, 7505.7, 242.96)
(15.1836, 52.5154, 10675.62, 270.4)
(16.8691, 46.9464, 10355.58, 208.85)
(-84.5779, 33.3414, 685.8, 48.02)
(-93.4152, 45.2257, 3665.22, 158.23)
(-82.2135, 32.2409, 10988.04, 232.62)
(6.5614, 49.669, 11277.6, 235.39)
(5.5716, 44.1215, 8549.64, 235)
(35.3735, 31.2834, 2042.16, 83.44)
(-16.4213, 15.9828, 6964.68, 222.26)
(-98.709, 27.7313, 2415.54, 130.56)
(15.1433, 41.6544, 11285.22, 241.75)
(-47.466, -21.2352, 1866.9, 84.38)
(-96.6295, 19.973, 5806.44, 173.7)
(22.1038, 45.3011, 9624.06, 187.25)
(48.7503, 61.8188, 10363.2, 237.3)
(8.6082, 51.5337, 8648.7, 203.32)
(23.3612, 37.9742, 632.46, 58.03)
(-5.12, 54.3651, 11879.58, 250.29)
(35.0382, 32.7643, 944.88, 44.17)
(12.9777, 49.6734, 10965.18, 203.5)
(12.2522, 52.2469, 11323.32, 193.33)
(4.7547, 52.3141, None, 8.23)
(18.376, 44.015, 10972.8, 264.73)
(15.8193, 49.3909, 10347.96, 198.11)
(134.3183, 34.7162, 9144, 232.84)
(35.9662, 31.7266, 1028.7, 91.89)
(14.7391, 32.366, 2468.88, 140.96)
(15.9601, 46.4333, 304.8, 39.18)
(-8.7856, 52.7671, 502.92, 93.63)
(-116.2106, 43.3997, 2049.78, 46.95)
(-47.0198, -24.6172, 9753.6, 212.36)
(-96.1116, 29.9817, 1402.08, 75.92)
(-7.1226, 40.6394, 10675.62, 232.62)
(24.6933, 47.4983, 9753.6, 216.65)
(18.7046, 47.0671, 9471.66, 252.7)
(22.026, 45.9033, 10972.8, 199.05)
(-77.9794, 39.4767, 205.74, 7.72)
(-108.5102, 45.8003, 1097.28, 34.59)
(24.492, 36.7402, 1447.8, 46.27)
(-79.6278, 43.6901, 190.5, 0.45)
(3.2033, 49.8985, 11285.22, 219.26)
(-2.1166, 37.626, 7871.46, 221.71)
(19.8037, 50.0745, None, 3.34)
(18.2329, 47.8171, 10668, 280.49)
(-1.3552, 50.9531, None, 9.26)
(-4.0262, 43.5619, 10668, 232.2)
(4.5376, 51.3681, 11277.6, 232.88)
(-81.2763, 29.2268, 548.64, 55.41)
(-67.0075, 18.5064, 5234.94, 209.42)
(7.1282, 47.8707, 10058.4, 251.8)
(-76.1239, 41.0243, 670.56, 83.3)
(-0.293, 38.358, 2491.74, 153.75)
(-96.2408, 19.2805, 10668, 238.49)
(-90.8352, 35.5192, None, 74.77)
(9.0213, 44.7524, 5852.16, 169.16)
(12.1059, 45.6251, 358.14, 71.36)
(15.8626, 46.5702, 11582.4, 191.49)
(-76.5871, 42.6426, 8229.6, 230.07)
(-84.4028, 27.5966, 11582.4, 227.12)
(69.0477, 18.4885, 10050.78, 237.39)
(13.7327, 57.0648, 10965.18, 204.31)
(8.486, 48.4079, 6682.74, 210.07)
(88.022, 21.7076, 8648.7, 227.44)
(11.4981, 52.2749, 6697.98, 226.73)
(77.8802, 27.9457, 7833.36, 227.38)
(17.0351, 41.2347, 10668, 246.58)
(14.7425, 42.6953, 10980.42, 231.03)
(-84.891, 34.4641, 1615.44, 71.18)
(21.6544, 43.5377, 9646.92, 186.36)
(16.4964, 32.2446, 7307.58, 137.52)
(11.7776, 49.8996, 0, 39.06)
(8.226, 47.4531, 556.26, 60.84)
(-60.2088, -32.2044, 9144, 215.98)
(15.3708, 47.3737, 3657.6, 98.14)
(-77.501, 38.9954, 11582.4, 214.36)
(14.8391, 46.1887, 5684.52, 236.9)
(-26.6873, 63.6361, 7315.2, 136.33)
(116.4848, 39.1274, 8869.68, 241.44)
(12.6793, 47.8507, 1043.94, 37.96)
(118.0884, 21.306, 11582.4, 257.15)
(-73.8634, 40.7724, None, 0)
(-82.1313, 29.8707, 7924.8, 220.96)
(-0.4278, 51.3561, 1821.18, 142.61)
(-81.697, 30.394, 1722.12, 146.96)
(-1.5645, 52.0149, 1676.4, 26.74)
(-73.6986, 41.0562, 144.78, 44.47)
(77.2066, 26.087, 10355.58, 244.74)
(-81.3012, 35.419, 11269.98, 244.05)
(-81.8026, 25.9721, 1371.6, 55.92)
(77.1697, 28.5687, 640.08, 72.04)
(-43.2923, -22.7935, 137.16, 75.65)
(-96.6959, 33.0042, 10980.42, 229.39)
(-43.5248, -22.739, 1798.32, 112.32)
(-84.7538, 33.2961, 304.8, 41.83)
(-78.728, 42.9416, 205.74, 65.12)
(-82.1903, 34.8814, 10668, 244.06)
(77.2623, 14.1744, 9441.18, 182.77)
(9.8103, 51.7891, 11590.02, 215.88)
(6.8633, 52.246, 10972.8, 215.05)
(-126.2001, 43.5837, 11269.98, 229.14)
(-0.6487, 50.7378, 4236.72, 168)
(106.3963, -6.0095, 2415.54, 125.53)
(-90.3593, 38.7383, None, 0)
(30.8221, 38.4125, 11582.4, 244.89)
(-74.1929, 40.7005, 243.84, 46.03)
(-103.5795, 38.8785, 8763, 224.04)
(-1.7621, 51.1474, 182.88, 79.57)
(106.0511, -5.6153, 10972.8, 242.86)
(-1.2036, 51.6815, 10972.8, 243.05)
(8.9834, 50.4408, 1257.3, 53.11)
(-88.1712, 29.1606, 10363.2, 195.57)
(-0.7232, 57.4997, 586.74, 73.12)
(-123.1805, 49.1907, None, 3.6)
(-85.7991, 28.0473, 10972.8, 226.29)
(72.7226, 19.3194, 4259.58, 177.89)
(-76.7179, 39.9225, 9753.6, 217.66)
(-86.1297, 39.8504, 906.78, 95.33)
(-121.0214, 45.5264, 5509.26, 194.48)
(54.9895, 24.9913, 6492.24, 123.25)
(86.9744, 22.9635, 9425.94, 204.86)
(-86.7312, 36.0043, 8229.6, 230.93)
(-70.7909, 47.8392, 10972.8, 183.33)
(13.0502, 45.3918, 10965.18, 231.07)
(0.0086, 52.458, 1379.22, 54.06)
(-81.0361, 33.9022, 2103.12, 110.26)
(77.8698, 14.0355, 7528.56, 203.99)
(-88.2584, 42.2107, 3055.62, 190.5)
(6.5626, 50.2631, 7886.7, 250)
(1.6345, 53.8732, 754.38, 73.86)
(-79.2213, 38.435, 7551.42, 235.53)
(5.2713, 53.3974, 11887.2, 234.8)
(-79.2209, 42.0815, 8641.08, 219.75)
(-88.2681, 42.7081, 1844.04, 85.7)
(57.1449, 24.5527, 8221.98, 213.76)
(-0.8241, 52.4796, 1295.4, 43.49)
(-82.4082, 40.1423, 10668, 244.6)
(-99.6339, 32.1839, 11887.2, 229.46)
(-94.0594, 17.5913, 9304.02, 207.73)
(-119.4285, 34.8624, 7627.62, 238.93)
(1.9833, 49.8179, 11597.64, 231.36)
(-22.5683, 62.5047, 10363.2, 260.11)
(-46.6498, -23.6306, None, 0)
(5.5419, 46.4542, 5394.96, 205.97)
(8.6422, 50.058, 464.82, 95.66)
(11.2888, 43.5847, 1295.4, 85.6)
(5.1387, 51.9306, 11277.6, 266.89)
(-49.5186, -27.5703, 10972.8, 196.05)
(-87.7274, 36.4598, 12192, 240.3)
(-72.9935, 41.5839, 10919.46, 223.02)
(23.0029, 37.9497, 10972.8, 218.52)
(-81.3286, 28.5484, None, 7.2)
(-5.1715, 50.347, 342.9, 39.01)
(76.832, 28.5052, 2834.64, 163.73)
(34.9564, 31.8512, 365.76, 55.98)
(-0.6791, 53.8175, 11285.22, 261.94)
(-40.2861, -20.2561, None, 2.06)
(8.5359, 50.0365, None, 12.86)
(139.8086, 35.5348, 129.54, 89.82)
(-3.4749, 57.2403, 10363.2, 244.46)
(6.7714, 51.2841, None, 2.83)
(-84.5649, 39.7367, 10058.4, 237.31)
(13.9454, 43.8949, 10972.8, 214.62)
(49.5495, 26.991, 9776.46, 248.58)
(38.9924, 32.0975, 10363.2, 244)
(-44.2827, -23.1966, 5326.38, 219.47)
(76.1654, 27.2509, 8823.96, 231.52)
(-85.2638, 33.0012, 6042.66, 213.32)
(-88.0067, 42.9563, 1211.58, 107.43)
(-82.1112, 34.9451, 1432.56, 65.95)
(-53.7873, -13.6005, 9753.6, 202.47)
(-6.9088, 56.7863, 8656.32, 205.58)
(23.5854, 61.2617, 1036.32, 83.35)
(3.9147, 52.4976, 11269.98, 216.75)
(-83.246, 29.6475, 10835.64, 240.77)
(6.7565, 51.2795, None, 3.09)
(-87.791, 43.0913, 9136.38, 213.08)
(-47.6344, -22.6913, 2743.2, 100.69)
(-0.9942, 47.2731, 10363.2, 241.03)
(1.9607, 41.0981, 2446.02, 147.27)
(-1.997, 48.3753, 10363.2, 239.58)
(142.5097, 36.6792, 10058.4, 268.23)
(17.3622, 36.346, 1988.82, 81.3)
(12.4114, 51.2655, 670.56, 47.1)
(-83.5959, 34.8421, 8366.76, 229.67)
(-77.1283, 38.9398, 579.12, 84.26)
(-46.4929, -23.4404, 708.66, 81.55)
(-82.1887, 28.4907, 7383.78, 229.84)
(-1.381, 51.0616, 5600.7, 154.88)
(-46.0226, -20.7768, 8221.98, 258.89)
(-83.6941, 30.0842, 2537.46, 62.86)
(4.352, 55.3644, 11277.6, 243.68)
(1.7499, 52.0365, 11887.2, 249.52)
(0.7085, 50.9906, 3421.38, 157.63)
(1.2322, 44.0732, 11277.6, 224.89)
(-0.5506, 38.2852, None, 3.6)
(-101.0293, 17.6062, 8130.54, 196.88)
(-73.8327, 42.4573, 9745.98, 242.35)
(23.7727, 37.5069, 822.96, 47.72)
(10.0831, 45.0288, 9745.98, 239.56)
(6.0906, 45.7711, 11887.2, 225.47)
(8.6372, 46.0448, 10660.38, 238.18)
(11.2663, 58.6552, 11117.58, 219.42)
(-73.0525, 40.8014, 335.28, 58.58)
(-83.38, 31.7034, 0, 40.56)
(-75.5899, 6.2191, None, 0)
(-49.2927, -25.387, 1752.6, 108.42)
(-0.431, 39.6205, 6880.86, 198.73)
(9.0789, 55.2405, 11582.4, 235.75)
(0.8817, 46.8907, 11582.4, 246.82)
(-84.2178, 29.7351, 10058.4, 241.21)
(30.2432, 37.4968, 6507.48, 166.34)
(-87.92, 41.9674, None, 5.66)
(None, None, None, 284.8)
(91.1973, 25.7461, 5326.38, 193.28)
(21.1947, 48.8479, 10668, 278.89)
(5.6518, 60.907, 11582.4, 246.62)
(22.3253, 38.1631, 5486.4, 104.95)
(12.2008, 55.6761, 2049.78, 167.71)
(-80.1345, 34.7474, 2407.92, 133.7)
(-85.2525, 32.7233, 10050.78, 235)
(-80.7014, 27.7303, 762, 51.24)
(-80.1601, 31.0269, 10363.2, 226.37)
(-157.8432, 21.1963, 1562.1, 127.63)
(8.2906, 48.2574, 10126.98, 238.07)
(-77.8496, 44.7769, 13098.78, 204.68)
(11.7389, 60.411, 10972.8, 216.35)
(19.3333, 56.4061, 7315.2, 227.86)
(-83.0293, 35.3636, 7315.2, 217.08)
(-81.0183, 34.0443, 10972.8, 224.2)
(7.7424, 51.9192, 9151.62, 226.22)
(18.4329, 54.3855, 7962.9, 81.49)
(101.1574, 11.2315, 10668, 237.43)
(-0.1487, 51.2781, 655.32, 30.19)
(-88.8449, 37.2284, 9745.98, 246.13)
(76.8293, 30.4306, 8961.12, 241.84)
(5.9179, 59.3491, 2392.68, 150.35)
(-81.5212, 28.7866, 678.18, 43.52)
(-93.2444, 44.9322, 853.44, 110.78)
(37.4038, 41.7931, 10370.82, 225.49)
(14.3643, 50.0505, 746.76, 85.41)
(10.5356, 53.8789, 11132.82, 243.37)
(-8.6239, 41.3598, 1485.9, 143.98)
(18.0605, 42.5131, 1249.68, 125.43)
(12.9965, 49.8071, 10363.2, 201.34)
(7.9638, 50.5093, 9753.6, 228.3)
(-1.1377, 53.725, 678.18, 19.34)
(5.6955, 50.1508, 13106.4, 240.96)
(10.116, 52.0827, 10972.8, 216.53)
(30.8989, 37.7092, 4084.32, 146.13)
(14.9844, 43.8511, 11582.4, 204.36)
(10.4938, 47.9743, 1485.9, 115.24)
(-75.6169, 37.853, 8084.82, 232.86)
(24.7233, 49.5365, 10957.56, 509.46)
(17.9249, 59.6469, None, 5.4)
(-87.495, 37.9334, 10972.8, 236.31)
(16.1065, 47.5349, 1188.72, 61.85)
(-120.0452, 37.9296, 9906, 218.63)
(-90.9383, 32.7278, 11582.4, 237.65)
(10.2747, 41.94, 8549.64, 239.48)
(18.5172, 57.2707, 11277.6, 244.75)
(19.1624, 44.8635, 11277.6, 281.96)
(14.0245, 53.7087, 11582.4, 260.73)
(77.2673, 28.5663, 1036.32, 88.01)
(77.7616, 13.1892, 1112.52, 74.61)
(-91.1766, 36.3082, 12192, 245.12)
(16.1991, 32.6701, 9753.6, 240.25)
(17.2154, 34.1631, 10363.2, 238.41)
(4.8714, 44.7728, 1066.8, 52.29)
(-83.3794, 31.4514, 9182.1, 206.35)
(-83.9621, 31.5471, 11582.4, 247.44)
(-122.2123, 37.71, None, 0)
(13.2763, 32.9031, None, 5.4)
(72.7537, 23.8391, 6324.6, 206.64)
(-83.7123, 34.0874, 1036.32, 63.36)
(141.758, 41.9025, 6743.7, 206.66)

In [ ]:
#unix_time(-date)

In [ ]:
# def unix_time(date):
#     year = date.dt.year
#     month = month.dt.month
#     day = day.dt.day
#     begin = int(datetime(year, month, day, 0, 0, tzinfo=timezone.utc).timestamp())
#     end = int(datetime(year, month, day, 10, 0, tzinfo=timezone.utc).timestamp())
#     print(begin)
#     print(end)

In [114]:
with open("credentials.json") as f:
    creds = json.load(f)

CLIENT_ID = creds["client_id"]
CLIENT_SECRET = creds["client_secret"]

TOKEN_URL = "https://auth.opensky-network.org/auth/realms/opensky-network/protocol/openid-connect/token"
API_URL = "https://opensky-network.org/api/flights/arrival"

def get_token():
    r = requests.post(
        TOKEN_URL,
        data={
            "grant_type": "client_credentials",
            "client_id": CLIENT_ID,
            "client_secret": CLIENT_SECRET,
        },
    )
    r.raise_for_status()
    return r.json()["access_token"]

token = get_token()

In [112]:
def get_flights(airport, begin, end):
    token = get_token()
    headers = {"Authorization": f"Bearer {token}"}
    resp = requests.get(
        API_URL,
        params={"airport": airport, "begin": begin, "end": end},
        headers=headers,
    )
 
    if resp.status_code == 404:
        print("No flights found for this window.")
        return []
 
    resp.raise_for_status()
    return resp.json()
 
 
if __name__ == "__main__":
    airport = "MMMX"  # Mexico City International Airport
    begin = 1781049600
    end = 1781053200
 
    flights = get_flights(airport, begin, end)
    print(f"{len(flights)} flights found for {airport}")
 
    for f in flights:
        print(f)

24 flights found for MMMX
{'icao24': 'aa9bb7', 'firstSeen': 1781011954, 'estDepartureAirport': 'LEBL', 'lastSeen': 1781053045, 'estArrivalAirport': 'MMMX', 'callsign': 'AMX038  ', 'estDepartureAirportHorizDistance': 1482, 'estDepartureAirportVertDistance': 34, 'estArrivalAirportHorizDistance': 1858, 'estArrivalAirportVertDistance': 58, 'departureAirportCandidatesCount': 0, 'arrivalAirportCandidatesCount': 1}
{'icao24': '0d0f91', 'firstSeen': 1781051529, 'estDepartureAirport': None, 'lastSeen': 1781052892, 'estArrivalAirport': 'MMMX', 'callsign': 'VIV1169 ', 'estDepartureAirportHorizDistance': None, 'estDepartureAirportVertDistance': None, 'estArrivalAirportHorizDistance': 345, 'estArrivalAirportVertDistance': 96, 'departureAirportCandidatesCount': 0, 'arrivalAirportCandidatesCount': 1}
{'icao24': 'a1245e', 'firstSeen': 1781039389, 'estDepartureAirport': 'KIAD', 'lastSeen': 1781052714, 'estArrivalAirport': 'MMMX', 'callsign': 'AMX456  ', 'estDepartureAirportHorizDistance': 1609, 'estDepartureAirportVertDistance': 56, 'estArrivalAirportHorizDistance': 2065, 'estArrivalAirportVertDistance': 42, 'departureAirportCandidatesCount': 2, 'arrivalAirportCandidatesCount': 1}
{'icao24': 'ab2728', 'firstSeen': 1781038012, 'estDepartureAirport': 'SKBO', 'lastSeen': 1781052444, 'estArrivalAirport': 'MMMX', 'callsign': 'AVA022  ', 'estDepartureAirportHorizDistance': 1390, 'estDepartureAirportVertDistance': 49, 'estArrivalAirportHorizDistance': 355, 'estArrivalAirportVertDistance': 111, 'departureAirportCandidatesCount': 0, 'arrivalAirportCandidatesCount': 1}
{'icao24': 'a01820', 'firstSeen': 1781039567, 'estDepartureAirport': 'KORD', 'lastSeen': 1781052246, 'estArrivalAirport': 'MMMX', 'callsign': 'AMX687  ', 'estDepartureAirportHorizDistance': 3084, 'estDepartureAirportVertDistance': 153, 'estArrivalAirportHorizDistance': 1787, 'estArrivalAirportVertDistance': 58, 'departureAirportCandidatesCount': 0, 'arrivalAirportCandidatesCount': 1}
{'icao24': '0d112e', 'firstSeen': 1781042590, 'estDepartureAirport': None, 'lastSeen': 1781052073, 'estArrivalAirport': 'MMMX', 'callsign': 'AMX751  ', 'estDepartureAirportHorizDistance': None, 'estDepartureAirportVertDistance': None, 'estArrivalAirportHorizDistance': 1112, 'estArrivalAirportVertDistance': 88, 'departureAirportCandidatesCount': 0, 'arrivalAirportCandidatesCount': 1}
{'icao24': 'ad4eb4', 'firstSeen': 1781046325, 'estDepartureAirport': 'MGGT', 'lastSeen': 1781051961, 'estArrivalAirport': 'MMMX', 'callsign': 'AMX679  ', 'estDepartureAirportHorizDistance': 1144, 'estDepartureAirportVertDistance': 38, 'estArrivalAirportHorizDistance': 425, 'estArrivalAirportVertDistance': 103, 'departureAirportCandidatesCount': 0, 'arrivalAirportCandidatesCount': 1}
{'icao24': '0d0ecf', 'firstSeen': 1781049483, 'estDepartureAirport': 'MMVR', 'lastSeen': 1781051848, 'estArrivalAirport': 'MMMX', 'callsign': 'VIV1427 ', 'estDepartureAirportHorizDistance': 476, 'estDepartureAirportVertDistance': 132, 'estArrivalAirportHorizDistance': 563, 'estArrivalAirportVertDistance': 96, 'departureAirportCandidatesCount': 0, 'arrivalAirportCandidatesCount': 1}
{'icao24': 'ab7267', 'firstSeen': 1781045046, 'estDepartureAirport': 'MMUN', 'lastSeen': 1781051682, 'estArrivalAirport': 'MMMX', 'callsign': 'AMX547  ', 'estDepartureAirportHorizDistance': 518, 'estDepartureAirportVertDistance': 39, 'estArrivalAirportHorizDistance': 1398, 'estArrivalAirportVertDistance': 81, 'departureAirportCandidatesCount': 0, 'arrivalAirportCandidatesCount': 1}
{'icao24': 'ab1bfb', 'firstSeen': 1781047665, 'estDepartureAirport': 'MMMY', 'lastSeen': 1781051511, 'estArrivalAirport': 'MMMX', 'callsign': 'AMX973  ', 'estDepartureAirportHorizDistance': 601, 'estDepartureAirportVertDistance': 14, 'estArrivalAirportHorizDistance': 2837, 'estArrivalAirportVertDistance': 4, 'departureAirportCandidatesCount': 0, 'arrivalAirportCandidatesCount': 1}
{'icao24': '0d0a08', 'firstSeen': 1781047448, 'estDepartureAirport': 'MMMY', 'lastSeen': 1781051427, 'estArrivalAirport': 'MMMX', 'callsign': 'VOI243  ', 'estDepartureAirportHorizDistance': 356, 'estDepartureAirportVertDistance': 14, 'estArrivalAirportHorizDistance': 371, 'estArrivalAirportVertDistance': 96, 'departureAirportCandidatesCount': 0, 'arrivalAirportCandidatesCount': 1}
{'icao24': '0d0ae8', 'firstSeen': 1781048231, 'estDepartureAirport': None, 'lastSeen': 1781051254, 'estArrivalAirport': 'MMMX', 'callsign': 'SLI325  ', 'estDepartureAirportHorizDistance': None, 'estDepartureAirportVertDistance': None, 'estArrivalAirportHorizDistance': 2744, 'estArrivalAirportVertDistance': 12, 'departureAirportCandidatesCount': 0, 'arrivalAirportCandidatesCount': 1}
{'icao24': '0d0ff6', 'firstSeen': 1781049650, 'estDepartureAirport': None, 'lastSeen': 1781050998, 'estArrivalAirport': 'MMMX', 'callsign': 'AMX245  ', 'estDepartureAirportHorizDistance': None, 'estDepartureAirportVertDistance': None, 'estArrivalAirportHorizDistance': 1316, 'estArrivalAirportVertDistance': 81, 'departureAirportCandidatesCount': 0, 'arrivalAirportCandidatesCount': 1}
{'icao24': '0d0e5a', 'firstSeen': 1781044606, 'estDepartureAirport': 'KSAT', 'lastSeen': 1781050907, 'estArrivalAirport': 'MMMX', 'callsign': 'VIV165  ', 'estDepartureAirportHorizDistance': 2490, 'estDepartureAirportVertDistance': 172, 'estArrivalAirportHorizDistance': 1275, 'estArrivalAirportVertDistance': 81, 'departureAirportCandidatesCount': 1, 'arrivalAirportCandidatesCount': 1}
{'icao24': 'a1244b', 'firstSeen': 1781033569, 'estDepartureAirport': 'KEWR', 'lastSeen': 1781050767, 'estArrivalAirport': 'MMMX', 'callsign': 'UAL1065 ', 'estDepartureAirportHorizDistance': 1314, 'estDepartureAirportVertDistance': 35, 'estArrivalAirportHorizDistance': 2044, 'estArrivalAirportVertDistance': 42, 'departureAirportCandidatesCount': 1, 'arrivalAirportCandidatesCount': 1}
{'icao24': '0d0d92', 'firstSeen': 1781047623, 'estDepartureAirport': None, 'lastSeen': 1781050709, 'estArrivalAirport': 'MMMX', 'callsign': 'VOI227  ', 'estDepartureAirportHorizDistance': None, 'estDepartureAirportVertDistance': None, 'estArrivalAirportHorizDistance': 307, 'estArrivalAirportVertDistance': 103, 'departureAirportCandidatesCount': 0, 'arrivalAirportCandidatesCount': 1}
{'icao24': '0d0acd', 'firstSeen': 1781039027, 'estDepartureAirport': 'KLAX', 'lastSeen': 1781050557, 'estArrivalAirport': 'MMMX', 'callsign': 'AMX645  ', 'estDepartureAirportHorizDistance': 2320, 'estDepartureAirportVertDistance': 106, 'estArrivalAirportHorizDistance': 1290, 'estArrivalAirportVertDistance': 81, 'departureAirportCandidatesCount': 2, 'arrivalAirportCandidatesCount': 1}
{'icao24': 'a445d9', 'firstSeen': 1781040440, 'estDepartureAirport': 'KATL', 'lastSeen': 1781050408, 'estArrivalAirport': 'MMMX', 'callsign': 'DAL585  ', 'estDepartureAirportHorizDistance': 1629, 'estDepartureAirportVertDistance': 53, 'estArrivalAirportHorizDistance': 2352, 'estArrivalAirportVertDistance': 27, 'departureAirportCandidatesCount': 0, 'arrivalAirportCandidatesCount': 1}
{'icao24': '0d121d', 'firstSeen': 1781038491, 'estDepartureAirport': 'KLAS', 'lastSeen': 1781050266, 'estArrivalAirport': 'MMMX', 'callsign': 'AMX481  ', 'estDepartureAirportHorizDistance': 1315, 'estDepartureAirportVertDistance': 13, 'estArrivalAirportHorizDistance': 1282, 'estArrivalAirportVertDistance': 81, 'departureAirportCandidatesCount': 1, 'arrivalAirportCandidatesCount': 1}
{'icao24': '0d06de', 'firstSeen': 1781037573, 'estDepartureAirport': 'KRDU', 'lastSeen': 1781050187, 'estArrivalAirport': 'MMMX', 'callsign': 'SLI431  ', 'estDepartureAirportHorizDistance': 1620, 'estDepartureAirportVertDistance': 57, 'estArrivalAirportHorizDistance': 155, 'estArrivalAirportVertDistance': 96, 'departureAirportCandidatesCount': 1, 'arrivalAirportCandidatesCount': 1}
{'icao24': 'a609d4', 'firstSeen': 1781043687, 'estDepartureAirport': 'KIAH', 'lastSeen': 1781050074, 'estArrivalAirport': 'MMMX', 'callsign': 'UAL1028 ', 'estDepartureAirportHorizDistance': 2832, 'estDepartureAirportVertDistance': 282, 'estArrivalAirportHorizDistance': 201, 'estArrivalAirportVertDistance': 96, 'departureAirportCandidatesCount': 0, 'arrivalAirportCandidatesCount': 1}
{'icao24': 'a6cc54', 'firstSeen': 1781039803, 'estDepartureAirport': 'KMIA', 'lastSeen': 1781049943, 'estArrivalAirport': 'MMMX', 'callsign': 'VOI791  ', 'estDepartureAirportHorizDistance': 2085, 'estDepartureAirportVertDistance': 142, 'estArrivalAirportHorizDistance': 1879, 'estArrivalAirportVertDistance': 65, 'departureAirportCandidatesCount': 1, 'arrivalAirportCandidatesCount': 1}
{'icao24': '0d11ed', 'firstSeen': 1781010725, 'estDepartureAirport': 'LFPG', 'lastSeen': 1781049801, 'estArrivalAirport': 'MMMX', 'callsign': 'AMX006  ', 'estDepartureAirportHorizDistance': 2833, 'estDepartureAirportVertDistance': 55, 'estArrivalAirportHorizDistance': 1596, 'estArrivalAirportVertDistance': 65, 'departureAirportCandidatesCount': 2, 'arrivalAirportCandidatesCount': 1}
{'icao24': '0d0804', 'firstSeen': 1781047580, 'estDepartureAirport': None, 'lastSeen': 1781049694, 'estArrivalAirport': 'MMMX', 'callsign': 'AMX1417 ', 'estDepartureAirportHorizDistance': None, 'estDepartureAirportVertDistance': None, 'estArrivalAirportHorizDistance': 1309, 'estArrivalAirportVertDistance': 81, 'departureAirportCandidatesCount': 0, 'arrivalAirportCandidatesCount': 1}

In [92]:
#hiding my airlab api key 
load_dotenv()

True

In [93]:
api_key_airlab = os.environ["api_key_airlab"]

In [94]:
api_key_airlab[:9]+"..."

'39f9f1b1-...'

## analysing ITA database https://www.trade.gov/us-international-air-travel-statistics-i-92-data

In [97]:
pip install pandas openpyxl

Requirement already satisfied: pandas in C:\Users\samue\.venvs\lede\Lib\site-packages (3.0.3)
Requirement already satisfied: openpyxl in C:\Users\samue\.venvs\lede\Lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\samue\.venvs\lede\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\samue\.venvs\lede\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\samue\.venvs\lede\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: et-xmlfile in C:\Users\samue\.venvs\lede\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in C:\Users\samue\.venvs\lede\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [102]:
ita = pd.read_excel("ITA.xlsx", header=3)

In [103]:
ita.head()

,Regions,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,YTD,YTD (1),Share
0,Europe,971828,936337,1636773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3544938,0.044818,0.1444
1,Caribbean,851394,924719,1178575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2954688,-0.020855,0.120356
2,Asia,597825,577694,805164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1980683,0.102466,0.080681
3,South America,261135,273955,313664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,848754,0.00102,0.034573
4,Central America,467792,465191,579988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1512971,0.103998,0.061629

In [106]:
ita_2 = pd.read_excel("ITA_monthly.xlsx")

In [107]:
ita_2.head()

,U.S. CITIZEN TRAVEL TO INTERNATIONAL REGIONS,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,"Released: June 17, 2026",NaN,NaN,NaN,NaN,NaN,NaN,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YTD
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,% Change,Market
2,Regions,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,YTD,YTD (1),Share
3,Europe,971828,936337,1636773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3544938,0.044818,0.1444
4,Caribbean,851394,924719,1178575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2954688,-0.020855,0.120356